#!/bin/bash

set -e

bold=`tput bold`
normal=`tput sgr0`

for file in $(ls -t *_test.ml)
do
	name=$(echo $file | sed -e 's/\.ml$//')
	target=$name.d.byte
	if ! ocamlbuild -no-links -nothing-should-be-rebuilt $target >/dev/null
	then
		echo "$bold>>> $name$normal"
		if ! OCAMLRUNPARAM=b ocamlbuild -no-links $target --
		then
			rm _build/$target
		fi
	fi
done
