#!/bin/bash

set -e

bold=`tput bold`
normal=`tput sgr0`


for file in *_test.ml
do
	name=$(echo $file | sed -e 's/\.ml$//')
	echo "$bold>>> $name$normal"
	OCAMLRUNPARAM=b ocamlbuild -no-links $name.d.byte --
done
